language: ruby
env:
  - GEM=api
  - GEM=core
  - GEM=frontend
before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
script:
  - bundle install --quiet
  - bundle exec rake test_app
  - bundle exec rake spec
rvm:
  - 2.1
  - 2.2
  - 2.3.1
addons:
  code_climate:
    repo_token: 7b6a43d5fa6ad571f5674176b0b85a79f62bfb7a908eb8bdd52941566706770e
